// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuerySphere.Models;

public partial class OauthToken
{
    public int TokenId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string UserRole { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime ExpiresAt { get; set; }

    public int UserId { get; set; }
}