// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using QuerySphere.Models;

namespace QuerySphere.data;

public partial class QueryShpereDbContext : DbContext
{
    public QueryShpereDbContext()
    {
    }

    public QueryShpereDbContext(DbContextOptions<QueryShpereDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<OauthToken> OauthTokens { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=querhyspheredbserver.database.windows.net;Initial Catalog=QueryShpereDb;User ID=dev;Password=pooh2003!");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OauthToken>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("PK__OAuthTok__658FEE8AD8061E7B");

            entity.ToTable("OAuthTokens");

            entity.Property(e => e.TokenId).HasColumnName("TokenID");
            entity.Property(e => e.AccessToken)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.RefreshToken).HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.UserName).HasMaxLength(100);
            entity.Property(e => e.UserRole).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}